application: kube-prometheus-stack
clusterConfig:
  namespace: monitoring
chart:
  name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: 56.21.4
  values: |
