apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset-staging
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "git@github.com:zumo/gitops-applications.git"
        revision: main
        files:
          - path: "app/apps/apps-*.yaml"
  template:
    metadata:
      name: "{{application}}"
    spec:
      project: "default"
      source:
        chart: "{{chart.name}}"
        repoURL: "{{chart.repoURL}}"
        targetRevision: "{{chart.targetRevision}}"
        helm:
          releaseName: "{{chart.releaseName}}"
          values: |-
            {{chart.values }}
      destination:
        namespace: "{{clusterConfig.namespace }}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - "ServerSideApply=true"
          - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
      ignoreDifferences:
        - group: storage.k8s.io
          kind: CSIDriver
          jqPathExpressions:
            - .spec.seLinuxMount
