apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swiggy-app-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: " https://github.com/pilotgab/swiggle-clone-main.git"
    targetRevision: main
    path: "manifest/* .yaml"
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      autoSync: true
